### ISSUE TITLE
gradle\wrapper\gradle-wrapper.jar needs to be checked in to project

### ISSUE THREAD

**Issue by ekellstrand** [web3j/eea-sample-project#1]
Acceptance Criteria:
- add gradle\wrapper\gradle-wrapper.jar to project
- make sure gradlew runs after pulling a clean copy of the project

Steps to Reproduce:
- pull master
- run `./gradlew`
Expect: 
    Gradle runs and builds the project
Actual:
    Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Environment:
Win10Ent cmd.exe (but I don't expect it's windows-specific)

**Comment by iikirilov** [comment]
fixed
